version: 1.0.{build}

os:
 - Visual Studio 2013
 - Visual Studio 2015

configuration:
  - Release

build_script:
  - md build
  - cd build
  - cmake .. 
  - cmake --build . --config %CONFIGURATION%
  
test_script:
  - cmake --build . --config %CONFIGURATION% --target RUN_TESTS

after_build:
  - cmake --build . --config %CONFIGURATION% --target INSTALL 

  
